### ISSUE TITLE
Setup tool panel views for Avans

### ISSUE THREAD

**Issue by hexylena** [Avans-ATGM/infrastructure#19]
https://github.com/galaxyproject/galaxy/pull/12327 This is a fantastic feature in Galaxy, we should take advantage of it. Let's figure out what tool panel views will be useful for students. Maybe we can organise them by class? Or Department + Class? Something like this could make life easier for teaching.

![](https://user-images.githubusercontent.com/216771/128549086-b4ca62df-09dc-4640-9027-06f62133361e.png)

I could very much imagine a "..by class" section with our classes listed

**Comment by Dirowa** [comment]
I agree totally with the by class section (transcriptomics etc.)
But by Department will be kinda difficult due it is ever-changing per project they are doing, and we have the normal headers.
Or maybe something for later?

- [ ] filter documentation of available classes on brightspace
- [ ] list up tools required per class
- [ ] add yaml files of the requested layouts

**Comment by hexylena** [comment]
Sounds good to me @ by class only. Maybe ideas for later then.

**Comment by hexylena** [comment]
We can also extract a bit the tools needed for specific galaxy tutorials, so, let me know if that helps.

**Comment by hexylena** [comment]
I've set the milestone as next year, this really isn't important. Just a nice feature I found that we could do someday when we have time.

**Comment by Dirowa** [comment]
Good task for Sander?
