### ISSUE TITLE
grafana doesn't update anymore

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#20]
All nodes from grafana doesn't update anymore.
I think I might caused this issue when I accidentally let the server overrun with data when I was working on plusPFP database.

![image](https://user-images.githubusercontent.com/62692537/146776976-2a5f4841-72d1-4502-939f-07fb6e5489ef.png)

@hexylena is it possible for you to look at it together with me?

**Comment by hexylena** [comment]
Debugged together, telegraf is getting a 500 error because of a config option in influx that needs to be increased.
