### ISSUE TITLE
Setup a  (hot-data)backup system for student projects

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#25]
Since somethimes things go terrible wrong, due to the system, users or admins are we going to implement as discussed a backup system.

In every student project is an automated generated directory called ``` data_storage ```. We can use this as line to know what to keep backed up and what not. After creating the new backup the old backup will be deleted, or shall we keep two copy's to be sure?

As we are going to put the old galaxy offline i believe we can also use that machine as place where students can put their projects.

So i suggest the following backup scheme.

| Machine name                   | Backup generated on                | backup location                              | Backup start |
|--------------------------------|------------------------------------|----------------------------------------------|--------------|
| Midgard.bioinformatics-atgm.nl | galaxy.bioinformatics-atgm.nl      | //mount/sdb/project_backup/year/project_N/        | saturday     |
| galaxy.bioinformatics-atgm.nl  | asgard.bioinformatics-atgm.nl      | //mnt/TeacherFiles/project_backup/year/project_N/ | saturday     |
| asgard.bioinformatics-atgm.nl  | midgard.bioinformatics-atgm.ml     | //mnt/TeacherFiles/project_backup/year/Project_N/ | saturday     |

@hexylena  Do you have any opinions about this. otherwise i could just add it to the Avans role.

My idea without any testing
- set all playbook on only daily?
- make a new var: date '+%a' to get which date it is in the week
- perform sh script ( gunzipping, checksum5 and transfer to new host)
- table up is also in hostvar to who it backups?

- [x] Create systemD timer and service
- [x] Create Ansible role
- [x] Create Normal template run
- [x] Create initialising template
- [ ] Automate initalising of archive? (not sure if possible because password required of Archive_user)
- [x] Automated Archive User
- [x] Automate Deploying script
- [x] Create Archive backup user
- [x] Test Service and timer (tested logs and previous runs also with systemctl start)
- [x] Check where loggings go (go as root, systemclt -u student_project_backup.service)

**Comment by hexylena** [comment]
Here's the full script https://gist.github.com/hexylena/7c7dc2d60620527d0ee1cd1de2a5b678, I recommend wrapping it up

And then we should stick it on cron? Run on sat. am.

> set all playbook on only daily?

What did this mean?

**Comment by Dirowa** [comment]
Ah gotcha, 
Then i will do that, and thankyou for the script :)

well i was thinking adding it to the avans role, and then make the playbook all.yml run only daily. 
https://galaxy.bioinformatics-atgm.nl/jenkins

**Comment by hexylena** [comment]
Ah gotcha. My only concern there is it would make the playbook run times potentially quite high, so moving that to cron could be a good fit.

Cron is kind of annoying for logging though, and preventing duplicate jobs from running, so, even more optimally it could be a systemd-timer

```
10:21:03|[hxr@cosima:~]3$ cat /home/hxr/.config/systemd/user/backup.service;
[Unit]
Description=Backup
Wants=backup.timer

[Service]
Type=oneshot
ExecStart=/bin/bash /home/hxr/.bin/backup.sh

[Install]
WantedBy=multi-user.target
10:21:04|[hxr@cosima:~]$ cat /home/hxr/.config/systemd/user/backup.timer
[Unit]
Description=Backup
Requires=backup.service

[Timer]
Unit=backup.service
OnCalendar=Mon..Sun 12:00
Persistent=true

[Install]
WantedBy=timers.target
```

then whatever is output just goes to journalctl and is easy to find

**Comment by Dirowa** [comment]
okay sofar done:

- debug script which works now (so automated by a single command)
- created scrip to initialise new data archive if required. Did not yet automate this in Ansible but i must be sure it only runs one ? maybe use the stat function to see if the archive already exists, other wise run it (but password required)
- Created Borg_backup user who maintains all the archives

Todo:
- write readme
- test systemd service ( have to google how)
- find out / research loggings
- write monitoring to keep see if things work

**Comment by Dirowa** [comment]
update:
scripts works 👯 

![image](https://user-images.githubusercontent.com/62692537/150750939-6d2b7807-0e33-4c2e-8c65-30b3b62b4279.png)

*note, disabled laura directory due that she already put data into it

**Comment by hexylena** [comment]
awesome!

> find out / research loggings

check journalctl

**Comment by Dirowa** [comment]
it took way onger then i,m proud on but the systemctl loggings is accesible as root.
For some reason do i only have loggings of today and not saturday.

**Comment by hexylena** [comment]
```
# systemd-analyze calendar "sat 12:00"
  Original form: sat 12:00
Normalized form: Sat *-*-* 12:00:00
    Next elapse: Sat 2022-01-29 12:00:00 CET
       (in UTC): Sat 2022-01-29 11:00:00 UTC
       From now: 4 days left
# systemctl show student_project_backup.timer | grep -i next
NextElapseUSecRealtime=Sat 2022-01-29 12:00:00 CET
NextElapseUSecMonotonic=0
# systemctl show student_project_backup.timer | grep -i last
LastTriggerUSec=Sat 2022-01-22 12:00:05 CET
LastTriggerUSecMonotonic=0
# systemctl status student_project_backup.timer
● student_project_backup.timer - Backup
   Loaded: loaded (/etc/systemd/system/student_project_backup.timer; disabled; vendor preset: enabled)
   Active: active (waiting) since Mon 2022-01-24 11:17:30 CET; 5h 11min ago
  Trigger: Sat 2022-01-29 12:00:00 CET; 4 days left
```

looks ok to me

**Comment by hexylena** [comment]
```
root@asgard:/home/thor# journalctl -u student_project_backup | tail
jan 24 15:38:56 asgard.bioinformatics-atgm.nl bash[25454]: Chunk index:                   35251                35478
jan 24 15:38:56 asgard.bioinformatics-atgm.nl bash[25454]: ------------------------------------------------------------------------------
jan 24 15:38:56 asgard.bioinformatics-atgm.nl bash[25454]: terminating with success status, rc 0
jan 24 15:38:56 asgard.bioinformatics-atgm.nl bash[25454]: Mon Jan 24 15:38:56 CET 2022 Pruning repository of project-2022-Martijn
jan 24 15:38:58 asgard.bioinformatics-atgm.nl bash[25454]: Keeping archive: project-2022-Martijn-2022-01-24T15-38-53 Mon, 2022-01-24 15:38:55 [4bc3f11a59237655ec1e8201e7bf99ae5a4cdf29f051cea552925ffebf8af349]
jan 24 15:38:58 asgard.bioinformatics-atgm.nl bash[25454]: Pruning archive: project-2022-Martijn-2022-01-24T15-38-21 Mon, 2022-01-24 15:38:22 [8b707083ac7804b18bc01cffb65f2e01d18e2f44ab1ae2e765013a51c67f760d] (1/1)
jan 24 15:38:58 asgard.bioinformatics-atgm.nl bash[25454]: Keeping archive: project-2022-Martijn-2022-01-22T12-00-12 Sat, 2022-01-22 12:00:13 [372bdb9e985705c5e7e8a571e3c90b1b65b9ead77076c7e9d2eed5159ff08aa8]
jan 24 15:38:59 asgard.bioinformatics-atgm.nl bash[25454]: terminating with success status, rc 0
jan 24 15:38:59 asgard.bioinformatics-atgm.nl bash[25454]: Mon Jan 24 15:38:59 CET 2022 Backup and Prune finished successfully
jan 24 15:38:59 asgard.bioinformatics-atgm.nl systemd[1]: Started Backup.
```

that too

**Comment by hexylena** [comment]
nice!
