### ISSUE TITLE
Disk space issue 

### ISSUE THREAD

**Issue by hexylena** [Avans-ATGM/infrastructure#32]
- [x] cvmfs cache size was hilariously large https://github.com/Avans-ATGM/infrastructure/commit/a7b81fe7df35151673ea29da0ffd6f7e852883fb
- [x] `/srv/galaxy/var/tmp` is overly full, we should run `tmpwatch` on that folder. 
	- [x] Something like `tmpwatch -v -a --mtime --dirmtime 2d /srv/galaxy/var/tmp`
	- [x] need to install tmpwatch package
	- [x] and then should run it on cron every day or so
- [x] the dependencies folder is quite full. It's not possible to move it, we'd have to set a new directory and then manually trigger reinstalling the dependencies via the galaxy admin interface. Maybe something for carnival week or so? Or just after the semester because not worth it. This should move to `/data/dependencies/` or so.

**Comment by Dirowa** [comment]
@hexylena , shall i make it into an ansible role so we can just plug and play if we have other places / machines to watch on tmp files?

**Comment by hexylena** [comment]
Ja doe maar

**Comment by Dirowa** [comment]
Cron job is automaticly created and can be upgraded in the groupvars/all file. 
I will move the dependencies in the carnaval vacation

**Comment by Dirowa** [comment]
issue closed when the galaxy server was knocked out and moved the dependencies directory.
The symlink is refused when trying to conda enviroments. I propose we reinstall that once the minor bioinformatics is at it end
