### ISSUE TITLE
Cocalc Homework retrieval code

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#36]
#### Donny's usefull coding job for Helena

if one of the toas has some free time I'd like to request a quick program. Probably a 2h project for an experienced python person.

given an input file name

loop over every project in the /data/cocalc directory
find files matching that name ending in .ipynb

- [x] load the ipynb files as json

- [x] collate the results of each problem, check the code sections where the students entered their solutions (should be identifiable with the cell metadata)

- [x] generate a report (markdown / plaintext is fine) with:

   - for each problem
   - here are all of the student solutions (minus the ones which have no changes / just say return NotImplementedHere)

Use Case:

I want to see what all the students wrote in their homework without 1) opening each notebook individually, 2) knowing which student wrote what.****

**Comment by Dirowa** [comment]
@hexylena , is it all solutions or only the ones of the homework?

**Comment by hexylena** [comment]
Ahh thanks for making a nice issue :)

If it accepts any 'search term' then we could find anything, homework or during-class exercises, which I think is optimal. I think it should be run approximately like:

```
python script.py Day-2/data-science-math-loop
```

where the first argument is used to search through the entire path of discovered files.

**Comment by Dirowa** [comment]
@hexylena do you perhaps know where i could find the names of the projects? so you do have a name of each homework instead of a project code

**Comment by Dirowa** [comment]
sorry if i was unclear. but i was more looking into the get_username function to retrieve the acual user name of the project

**Comment by hexylena** [comment]
[discussed out of band, magic sql query solves everything]

**Comment by Dirowa** [comment]
Finisht script is in /Courses/bin/collect_solutions.py

Current problem with code: will not use previous created functions. ( example in trimming you create the function mean. ) Some students also use it by other homework problems, with the active homework it works)

Other bug. more misuse. is when the metadata of the cells are the otherway around
