### ISSUE TITLE
backup system to surf.sara.archive.nl

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#43]
Requested by Mm that we also create an backing up system to archive.surfsara.nl for non student projects.
problem: Borg is not installed on archive.surfsara.nl nor do i have the rights to do so.

what to do: create script
- [ ] tar.gz the requested file and encrypt with the borg password key
- [ ] send data over to correct location on archive . surf.sara.nl
- [ ] create a script to prune backups (like borg does)

what already done:
- [x] local backup is already initialised with borg

**Comment by hexylena** [comment]
just conda install it in your account in the archive.

**Comment by Dirowa** [comment]
okay so i,m writing a script, currently do i also encrypt all created tar.gz files with openssl. @hexylena do you got any experience with encryptions programs? is this one a yay or nay?

**Comment by Dirowa** [comment]
yeah sure :D. enjoy your holiday!

**Comment by hexylena** [comment]
so there's some options here:

- mount the archive via ssh-fs, and use borg to backup to the ssh-fs mounted path. Here nothing needs to be installed on the remote end. https://borgbackup.readthedocs.io/en/stable/faq.html#what-is-the-difference-between-a-repo-on-an-external-hard-drive-vs-repo-on-a-server it is slower, but, it's clearly done by others, too.
- ask them to install borg. I've looked [at their documentation](https://servicedesk.surf.nl/wiki/display/WIKI/Data+Archive) something like borg would fit well with the service they're offering, they may be willing to just install it for us if we make a compelling case.

I think "rebuild borg but by yourself" is the most time expensive option and most likely to require additional debugging and work in the future, so, let's not do that. Encrypting yourself also won't get the benefits of redup and space saving that borg will.

**Comment by Dirowa** [comment]
almost dont with the ssh-fs way. i need to update the monitoring.
@hexylena i,m thinking about changing the prune parameters to --keep-last (how many backups we want).
Otherwise we will think stockpile on montly backups until the year is over. or what do you think?

**Comment by Dirowa** [comment]
Done
add projects to the all groupvars and fill in
Also implemented into monitoring.
