### ISSUE TITLE
isengard server keep going down

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#45]
Problem, 
SSH connections suddently fails withouth a reason.
Also direct access by monitor is not available anymore so an hard reset is required.

usefull log found
```
Jun 30 14:12:10 isengard rasdaemon[1045]:            <...>-8     [000]     0.000202: mce_record:           2022-06-30 14:12:09 +0200 bank=d, status= 8c000040000800c0, MEMORY CONTROLLER MS_CHANNEL0_ERR Transaction: Memory scrubbing error Corrected patrol scrub error, mci=Corrected_error, mca=MemCtrl: , n_errors=1 memory_channel=0, cpu_type= Skylake server, cpu= 0, socketid= 0, misc= 908440004000086, addr= 1442bbc00, mcgstatus=0, mcgcap= 6000c14, apicid= 0
Jun 30 14:12:11 isengard rasdaemon[1045]: rasdaemon: mce_record store: 0x55b3d4ec3248
Jun 30 14:12:11 isengard rasdaemon[1045]: rasdaemon: register inserted at db 
```

So appearntly the ramstick is a bit broken ? or is it the tool chadi and freek uses. This problem occours every time if chadi and freek have been running their data pipeline. Anyhow i can't directly find an reason online but it has something to do with the RAM or CPU, shall i contact the vendors?

@hexylena what do you think?

**Comment by hexylena** [comment]
> Memory Demand and Patrol Scrubbing: Demand scrubbing is the ability to write corrected data back to the memory once a correctable error is detected on a read transaction. Patrol scrubbing proactively searches the system memory, repairing correctable errors. It prevents accumulation of single-bit errors. Thus, there are risks at disabling it.

This seems pretty normal, we have ECC ram, of course it can correct the error and we should let it. (It's typical, not necessary bad ram yet.)

**Comment by hexylena** [comment]
ok that's not normal

```
00034001010090, MEMORY CONTROLLER RD_CHANNEL0_ERR Transaction: Memory read error MscodDataRdErr, mci=Error_overflow Corrected_error, mca=M2M: , n_errors=13, cpu_type= Skylak>


00014001010090, MEMORY CONTROLLER RD_CHANNEL0_ERR Transaction: Memory read error MscodDataRdErr, mci=Error_overflow Corrected_error, mca=M2M: , n_errors=5, cpu_type= Skylake>

```

**Comment by hexylena** [comment]
> CMCI(Corrected Machine Check Interrupt) that Intel processor supports. Usually this disablement is not recommended, but it might be handy if your hardware is misbehaving. Note that you'll get more problems without CMCI than with due to the shared banks, i.e. you might get duplicated error logs.

**Comment by hexylena** [comment]
Let's do the memtest, it's in the grub boot menu. Reboot, hold shift, find memtest, run it. Post results.

**Comment by Dirowa** [comment]
mem test holds no results, 

I performed on GPU, CPU and memory the long version.
all seems to be fined.

My best solution goes to a killer script of one the students
