### ISSUE TITLE
Galaxy tutorial, Database disaster

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#51]
Write an galaxy tutorial about how to work with the galactic database incase of an disaster

Problem: we needed to montage a galaxy database.
Unfortunately this could not be done by the standard created database of galaxy.

what did we do:

1. login on the galaxy server as galaxy
2. enter the psql database by using ``` sudo -u galaxy psql ```
3. rename the current galaxy server to a new name
4. Create an new database named galaxy ( the name of the one which you renamed)
5. add the galaxy backup to the database with zcat
6. reload galaxy old database backup is now the the running one

**Comment by hexylena** [comment]
https://github.com/galaxyproject/ansible-postgresql/pull/30#issuecomment-963600656

**Comment by hexylena** [comment]
https://github.com/galaxyproject/training-material/pull/3779/commits/db96915cf2117145ddaed93a52d45bd4d20b4334 in this PR is a new tutorial that covers it a bit
