### ISSUE TITLE
Add to existing roles somewhere

### ISSUE THREAD

**Issue by hexylena** [Avans-ATGM/infrastructure#52]
This file needs to exist
```
cat /etc/pam.d/nginx
auth       include      common-auth
account    include      common-account
```

make sure `www-data` is added to the group `shadow`, then nginx must be restarted.

**Comment by hexylena** [comment]
and we should document in operations, that this `/~username` exists and `/~username/secure` exists and is authenticated by their username/password.

**Comment by Dirowa** [comment]
Currently is in the Avans Nginx index role.
Should be checked if it works corretly.
Probably something todo together with Sander
