### ISSUE TITLE
expand monitor archive

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#57]
Hi @sanderboden ,

Could you adjust the srcipt of monitor archive so that we have an overview of the main directories?
Add it to the current script:

Hint
```files=$(ssh dlvrins1@archive.surfsara.nl -i //etc/telegraf/.ssh/secret_SSH_key_archive 'ls //home/gringott/')```
Loop over it with the other commands and send to the database

**Comment by sanderboden** [comment]
incremental backup not allowed on surf, thus monitoring not needed
