### ISSUE TITLE
Setup Spider_Galaxy

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#6]

**Comment by Dirowa** [comment]
Just to create a clear message for my self:

- [ ] Install Spider Galaxy
- [ ] gain acces to Spider galaxy by website for testing 
- [ ] Install Decash through WebDev
- [ ] Install Pulsar server
- [ ] modify jon runner so it runs jobs op surfsara. lisa

**Comment by Dirowa** [comment]
@hexylena, i,m not sure if we discussed this. but should i ask surfsara helpdesk for the webdav or did i read/understand something incorrectly?

**Comment by hexylena** [comment]
I can help with that, we don't need to contact them for that yet I think.

**Comment by Dirowa** [comment]
For some reason does scp and Rsync only works when the commands come from our unix systems. we can send and retrieve files.

I asked the helpdesk to help me with the get-macaroons.
Error message: Login failed, and I,m pretty sure I type my correct password the wholetime

**Comment by hexylena** [comment]
well we can start with scp/rsync, that's good to know. That means we can mount the filesystem with `sshfs`, can you see if you can get that working?

Then we just set spider_galaxy's data directory to the remote filesystem with sshfs.

**Comment by Dirowa** [comment]
sshfs works :).

Shall i make an ansible role to automate this?

**Comment by hexylena** [comment]
fstab!

**Comment by Dirowa** [comment]
hi @hexylena  sshfs is automounted with reconnection in fstab.
I quess the next step is to install pulsar / rabbitMQ with a custom jobrunner?

**Comment by Dirowa** [comment]
Stale subject, can be contiunued once the ports are set open by DIF team
If they will allow it ( continious discussion)
